config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  resources :concerts

  resources :songs do
    collection do
      get 'search'
    end
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
end

app/models/composer.rb
class Composer < ActiveRecord::Base
  has_many :songs
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  belongs_to :place
  belongs_to :conductor
  belongs_to :orchestra
  has_many :concerts_song
  has_many :songs, through: :concerts_song
end

app/models/concerts_song.rb
class ConcertsSong < ActiveRecord::Base
end

app/models/conductor.rb
class Conductor < ActiveRecord::Base
  has_many  :concerts
end

app/models/orchestra.rb
class Orchestra < ActiveRecord::Base
  has_many :concerts
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :concerts
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :composer
  has_many :concerts_song
  has_many :concerts, through: :concerts_song

  scope :arr_youtube_id, -> {where('youtube_id is not null').pluck(:youtube_id)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def search
    @song = Song.find_by(youtube_id: params[:videoId])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    @concerts = Concert.all
    @youtube_ids = Song.arr_youtube_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LivetrailerMvp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/songs/search.js.erb
$("#now-playing p").replaceWith("<p><%=@song.composer.comp_name%>：<%=@song.title%></p>")

app/views/tops/_concert.html.erb
<li class="concert_<%=concert.id%>">
  <%= link_to concert.title, concert_path(concert.id) %>
</li>

app/views/tops/index.html.erb
<div id="song-box">
  <div id="player"></div>
  <div id="now-playing">
    <p>
    </p>
  </div>
</div>

<div class="concert-box">
  <ul>
    <%= render partial: 'concert', collection: @concerts%>
  </ul>
</div>

<script>
    var player;
    videoList = <%== @youtube_ids.to_json %>

    function loadPlayer() {
        if (document.querySelector('#player')) {
            // get API
            var tag = document.createElement('script'),
            firstScriptTag = document.getElementsByTagName('script')[0];
            tag.src = 'https://www.youtube.com/iframe_api';
            firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

                playCount = 0;


            function playChannel() {
                // init player
                player = new YT.Player(
                    'player',
                    {
                        width: '350',
                        height: '200',
                        videoId: videoList[0],
                        playerVars: {
                            rel: 1,
                            autoplay: 1,
                            disablekb: 0,
                            showsearch: 0,
                            showinfo: 0,
                            controls: 1,
                            autohide: 0,
                            modestbranding: 0,
                            wmode: 'opaque',
                            hd: 1,
                            html5: 1,
                            iv_load_policy: 3
                        },
                        events: {
                            'onReady'        : onPlayerReady,
                            'onStateChange'  : onPlayerStateChange,
                            'onError'        : error
                        }
                    }
                );

                // play video
                function onPlayerReady(e) {
                    console.log('onPlayerReady');
                    $('.concert-box ul li:eq(0)').css('backgroundColor', 'rgb(7, 206, 250)')
                    //ajax
                    $.ajax({
                      url: 'songs/search',
                      type: 'GET',
                      data: {videoId: videoList[playCount]}
                    })
                }

                function error(e) {
                    console.log('Error');
                    console.log(e);
                }
            }


            function onPlayerStateChange(e) {
                // get state
                console.log(e);

                // play list loop when video end play next video
                if (e.data === 0) {
                    $(".concert-box ul li" + ":eq("+playCount+")").css('backgroundColor', '');
                    playCount++;
                    if (playCount > (videoList.length -1)) {
                        playCount = 0;
                    }
                    player.loadVideoById(videoList[playCount]);
                    player.playVideo();
                    $(".concert-box ul li" + ":eq("+playCount+")").css('backgroundColor', 'rgba(70, 164, 242, 0.8)');
                    console.log(playCount)
                    $.ajax({
                      url: 'songs/search',
                      type: 'GET',
                      data: {videoId: videoList[playCount]}
                    })
                }

                // $('.concert-box ul li:eq(2)').css('backgroundColor', 'red');
            }

            function onYouTubeIframeAPIReady() {
                playChannel();
            }

            setTimeout(function() {
                onYouTubeIframeAPIReady();
            }, 1200);
        }
    }

    loadPlayer();
</script>